# Site settings
title: Jaap Bakker
email: jaap@j33p.nl
description: > # this means to ignore newlines until "baseurl:"
  I can guide your product make its first steps on the internet.  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: jaapbakker
github_username:  jaapbakker88

# Build settings
markdown: kramdown
