# Site settings
title: Under Construction
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ik heb een achtergrond in cultuur, een passie voor kunst 
  en programeren en ben beschikbaar voor werk. 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: jaapbakker
github_username:  jaapbakker88

# Build settings
markdown: kramdown
