# Site settings
title: Jaap
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  He is a newborn developer living in Amsterdam. <br />
  Read about him, then contact him. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: jaapbakker
github_username:  jaapbakker88

# Build settings
markdown: kramdown
