# Site settings
title: Jaap Bakker
email: jaap@j33p.nl
description: > # this means to ignore newlines until "baseurl:"
  I am a new born web developer specialized in a lot of stuff,<br />
  but the one you wouldn't expect: culture.  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: jaapbakker
github_username:  jaapbakker88

# Build settings
markdown: kramdown
